"""Rating-sweep proof artifact: SHOW the equity bar is rating-conditioned (task 0137).

The whole thesis is "equity conditioned on rating", but until now the only legible
demonstrations of conditioning were an internal monotonicity regression test
(``test_wdl_regression``) and the interactive web sliders — nothing committed and
CI-checkable that *shows* one fixed position's bar moving across a rating ladder.

This module is that proof. It evaluates a single, deliberately one-sided position at a
ladder of equal-rating rungs and reports the White-POV equity at each. The objective
centipawn input is identical at every rung (the material edge doesn't change), so a
**rating-blind** bar would print one flat number; the **rating-conditioned** ``wdl-a``
bar instead climbs with rating — stronger players convert the win, weaker players are
likelier to stalemate or bungle it. The climb *is* the conditioning, made visible.

``wdl-a`` is torch-free (it loads the committed JSON artifact and uses a deterministic
``MaterialEngine`` for cp), so the sweep — and the committed ``reports/rating_sweep.md``
it generates — is fully offline and reproducible. ``test_rating_sweep`` asserts both the
monotone direction and that the committed artifact stays byte-for-byte in sync.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import List, Sequence

from chess_equity.adapters import EquityModel

# The demonstration position: White has a queen against a lone black king — a crushing,
# unambiguous advantage whose cp input is the same at every rung. One fixed FEN so the
# artifact is a stable regression target.
DEMO_FEN = "4k3/8/8/8/8/8/8/3QK3 w - - 0 1"
# Equal-rating rungs from club to master, both players set to the rung so the only thing
# changing down the ladder is the rating context.
DEMO_RUNGS = (1000, 1500, 2000, 2500)
# The rating-conditioned, torch-free predictor the artifact pins.
DEMO_MODEL = "wdl-a"

# reports/rating_sweep.md at the repo root (src/chess_equity/validate/ -> parents[3]).
ARTIFACT_PATH = Path(__file__).resolve().parents[3] / "reports" / "rating_sweep.md"


@dataclass(frozen=True)
class Rung:
    """One rung of the sweep: both players at ``rating`` -> White-POV ``equity_white``."""

    rating: int
    equity_white: float


def parse_rungs(spec: str) -> List[int]:
    """Parse a ``"1000,1500,2000,2500"`` rating-rung spec into a list of ints.

    Raises ``ValueError`` on an empty spec or a non-integer / non-positive rung so the
    CLI surfaces a clean error instead of a stack trace.
    """
    rungs: List[int] = []
    for part in spec.split(","):
        part = part.strip()
        if not part:
            continue
        try:
            rung = int(part)
        except ValueError:
            raise ValueError(f"rating rung {part!r} is not an integer") from None
        if rung <= 0:
            raise ValueError(f"rating rung {rung} must be positive")
        rungs.append(rung)
    if not rungs:
        raise ValueError("no rating rungs given (expected e.g. 1000,1500,2000,2500)")
    return rungs


def sweep(model: EquityModel, fen: str, rungs: Sequence[int]) -> List[Rung]:
    """Evaluate ``fen`` at each rung (both players at the rung) -> White-POV equities."""
    return [Rung(r, model.evaluate(fen, r, r).equity_white) for r in rungs]


def render_text(fen: str, rungs: List[Rung]) -> str:
    """Plain-text sweep for the CLI: one ``rating -> equity`` line per rung + spread."""
    lines = [f"rating sweep — {fen}"]
    for rung in rungs:
        lines.append(f"  {rung.rating:>5}  {rung.equity_white:6.2f}%  (White-POV equity)")
    if len(rungs) >= 2:
        spread = rungs[-1].equity_white - rungs[0].equity_white
        lines.append(
            f"  spread {spread:+.2f} pts from {rungs[0].rating} to {rungs[-1].rating}"
        )
    return "\n".join(lines)


def render_markdown(fen: str, rungs: List[Rung], model_name: str = DEMO_MODEL) -> str:
    """The committed proof artifact: a self-explaining Markdown table of the sweep."""
    spec = ",".join(str(r.rating) for r in rungs)
    spread = rungs[-1].equity_white - rungs[0].equity_white
    lines = [
        "# Rating-sweep proof — the equity bar is rating-conditioned",
        "",
        f'_Generated by `chess-equity eval "{fen}" --rating-sweep {spec} '
        f"--model {model_name}`._",
        "_Regenerate with `python -m chess_equity.validate.rating_sweep` "
        "(a test asserts this file stays in sync)._",
        "",
        f"Position (White to move): `{fen}` — White has a queen against a lone king.",
        "",
        "The objective centipawn eval is identical at every rung (the material edge "
        "doesn't change). A **rating-blind** bar would therefore print one flat number. "
        f"The **rating-conditioned** `{model_name}` bar instead climbs with rating: "
        "stronger players convert the win more reliably, weaker players are likelier to "
        "stalemate or blunder it.",
        "",
        "| White Elo | Black Elo | White-POV equity |",
        "|--:|--:|--:|",
    ]
    for rung in rungs:
        lines.append(f"| {rung.rating} | {rung.rating} | {rung.equity_white:.2f}% |")
    lines += [
        "",
        f"Equity climbs **{spread:+.2f} points** from the {rungs[0].rating} rung to the "
        f"{rungs[-1].rating} rung — monotonically, and entirely from rating conditioning "
        "(the cp input is constant). That spread is the proof the bar is conditioned on "
        "rating, not just a re-skinned centipawn score.",
        "",
    ]
    return "\n".join(lines)


def generate_artifact(model: EquityModel | None = None) -> str:
    """Build the committed ``reports/rating_sweep.md`` content for the demo sweep."""
    if model is None:
        from chess_equity.wdl_regression import build_wdl_a_equity

        model = build_wdl_a_equity()
    rungs = sweep(model, DEMO_FEN, DEMO_RUNGS)
    return render_markdown(DEMO_FEN, rungs, DEMO_MODEL)


def write_artifact(path: Path = ARTIFACT_PATH) -> Path:
    """Regenerate the committed artifact on disk; returns the path written."""
    content = generate_artifact()
    path.write_text(content, encoding="utf-8")
    return path


if __name__ == "__main__":  # pragma: no cover - manual regeneration entry point
    written = write_artifact()
    print(f"wrote rating-sweep artifact to {written}")
